# Generated by Django 4.1.7 on 2023-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_born_date_user_city_user_country_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_with_ia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='why_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
